BASE: ['']
TRAIN_OR_TEST: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 2
  EPOCHS: 10
  LR: 1e-3
  MODEL_FILE_NAME: PURE_PURE_UBFC_tscan.pth
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: True               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/data1/toolbox_data/PURE/RawData"                # Raw data path, need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"         # Preprocessed data path
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 0.8
    PREPROCESS :
      DATA_TYPE: ['Normalized','Standardized']
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CLIP_LENGTH: 180
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: True                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data1/toolbox_data/PURE/RawData"   # need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"         # Preprocessed data path
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CLIP_LENGTH: 180
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/data1/toolbox_data/UBFC/RawData"     # need to be updated
    CACHED_PATH: "/data2/rppg_datasets/PreprocessedData/"         # Preprocessed data path
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'Normalized','Standardized' ]
      LABEL_TYPE: Normalized
      DO_CHUNK: True
      CLIP_LENGTH: 180
      DYNAMIC_DETECTION: False
      DETECTION_LENGTH: 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGER_BOX_SIZE: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  MODEL_PATH:   ""
                    # if TRAIN_OR_TEST:"train_and_test", should be "" or anything, it will use currently trained model.
                    # if TRAIN_OR_TEST:"only_test", should be "path"
