BASE: ['']
TOOLBOX_MODE: "signal_method"      # "train_and_test"  or "only_test" or "signal_method"
SIGNAL:
  METHOD: ["ICA", "POS", "CHROM", "GREEN", "LGI", "PBV"]
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/UBFC/RawData"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/rppg_toolbox/PreprocessedData"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
INFERENCE:
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
                  
